In [19]:
import numpy as np
kk=np.array([[1,2,3,4,5,6,7,8,9],[5,8,7,6,1,2,3,4,8]])
print(kk)
print(kk.ndim)
kr=kk[1,6:9]
print(kr)

[[1 2 3 4 5 6 7 8 9]
 [5 8 7 6 1 2 3 4 8]]
2
[3 4 8]


In [27]:
var1=np.array([[[1,2,3,4,5,6],[6,5,4,9,8,7]]])
print(var1)
print()
print(var1.ndim)
print()
print()
for i in var1:
    for j in i:
        for k in j:
            print(k)
    

[[[1 2 3 4 5 6]
  [6 5 4 9 8 7]]]

3


1
2
3
4
5
6
6
5
4
9
8
7


In [30]:
var2=np.array([[[1,2,3,4,5,6],[5,4,6,7,8,9],[6,5,4,9,8,7]]])
print(var2.shape)

(1, 3, 6)


In [35]:
var3=np.array([2,1,4,5,6,7,8,9])
print(var3.ndim)
x=var3.reshape(1,2,2)
x

1


ValueError: cannot reshape array of size 8 into shape (1,2,2)